#!/bin/bash

# Version 0.1.0, modified 04Nov2015 by Troy Conrad <troy.conrad@lbox.com>

# Based on commands from http://blog.yohanliyanage.com/2015/05/docker-clean-up-after-yourself/

sudo docker rm -v $(sudo docker ps -a -q -f status=exited)

sudo docker rmi $(sudo docker images -f "dangling=true" -q)

sudo docker run -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/docker:/var/lib/docker --rm martin/docker-cleanup-volumes